apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: { { .Values.service.type } }
  selector:
    app: backend
  ports:
    - name: http
      port: { { .Values.service.port } }
      targetPort: 8000
