name: Main Workflow

on:
  push:
    branches:
      - "**"

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yml
    with:
      ref: ${{ github.ref }}

  publish:
    if: ${{ success() }}
    needs: code-quality
    uses: ./.github/workflows/publish.yml
    with:
      ref: ${{ github.ref }}
