name: Main Workflow

on:
  push:
    branches:
      - "**"

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yml
    with:
      ref: ${{ github.ref }}

  tests:
    uses: ./.github/workflows/tests.yml
    needs: code-quality
    with:
      ref: ${{ github.ref }}

  build:
    uses: ./.github/workflows/build.yml
    needs: tests
    with:
      ref: ${{ github.ref }}

  publish:
    if: ${{ success() }}
    needs: build
    uses: ./.github/workflows/publish.yml
    with:
      ref: ${{ github.ref }}
