name: Publish Containers

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
        default: "main"

jobs:
  publish-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set version
        uses: ./.github/actions/version
      - name: print version
        run: echo ${{ env.CUSTOM_VERSION }}
