name: Publish Containers

on:
  workflow_run:
    workflows: ["code-quality.yml"]
    types:
      - completed

jobs:
  publish-artifacts:
    # Only run if code-quality.yml finished successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
