name: Publish Containers

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
        default: "main"
    secrets: inherit

jobs:
  publish-artifacts:
    # Only run if code-quality.yml finished successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
