name: Publish Containers

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
        default: "main"

jobs:
  publish-artifacts:
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set version
        uses: ./.github/actions/version
      - name: print version
        run: echo ${{ env.CUSTOM_VERSION }}
